

import PageContainer from "../app/PageContainer"

export default function Posts() {
    // const styles = {
    // }

    return (<PageContainer title="posts" content={
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec auctor massa, quis posuere lacus. Nullam nec laoreet nisi, sit amet vehicula orci. Vivamus ac risus in purus tincidunt euismod vel vitae est. Sed tellus lorem, commodo placerat velit nec, accumsan bibendum ante. Nunc non ipsum sed lectus fermentum ultricies. Sed eu lobortis lectus. Quisque tempus pharetra tortor, nec auctor ante. Phasellus porta sapien vel placerat porta. In eu cursus mi. Phasellus eu mauris lectus. Aenean laoreet rhoncus tortor, laoreet maximus est sodales id. Fusce aliquet, ipsum at commodo ultricies, lorem sem rhoncus est, nec suscipit risus lectus id dui. Etiam semper interdum rutrum. Mauris nec placerat felis, vitae ultrices est. Aliquam et nisl et eros fermentum condimentum.
Cras sed dignissim felis. Maecenas sodales tellus vitae orci placerat interdum. Suspendisse finibus venenatis dignissim. Sed sagittis massa pellentesque rhoncus ultricies. Sed convallis felis lacus, eget suscipit diam vehicula et. Aliquam pellentesque, quam et vestibulum ultricies, quam magna sagittis eros, id vehicula massa nulla in erat. Vestibulum eu facilisis neque, non feugiat neque. Duis condimentum congue pretium. Donec sit amet justo feugiat, ullamcorper ligula id, tempor eros. Sed vitae nulla laoreet, sagittis odio sit amet, porttitor elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer hendrerit, quam ac sodales lacinia, velit libero vulputate urna, et posuere felis nisl et dui. Nunc ut lobortis nisl.
Vivamus accumsan est a libero consectetur, eget pulvinar nunc pretium. Integer at eros quis sem egestas varius. Mauris laoreet convallis imperdiet. Cras quis orci efficitur, luctus tellus ut, pellentesque urna. Phasellus rhoncus pulvinar elementum. Fusce accumsan convallis orci, id ullamcorper nisl laoreet quis. Praesent porttitor magna a justo aliquet hendrerit. Aliquam quis quam augue. Mauris varius malesuada dolor in commodo.
Curabitur in est lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec auctor massa, quis posuere lacus. Nullam nec laoreet nisi, sit amet vehicula orci. Vivamus ac risus in purus tincidunt euismod vel vitae est. Sed tellus lorem, commodo placerat velit nec, accumsan bibendum ante. Nunc non ipsum sed lectus fermentum ultricies. Sed eu lobortis lectus. Quisque tempus pharetra tortor, nec auctor ante. Phasellus porta sapien vel placerat porta. In eu cursus mi. Phasellus eu mauris lectus. Aenean laoreet rhoncus tortor, laoreet maximus est sodales id. Fusce aliquet, ipsum at commodo ultricies, lorem sem rhoncus est, nec suscipit risus lectus id dui. Etiam semper interdum rutrum. Mauris nec placerat felis, vitae ultrices est. Aliquam et nisl et eros fermentum condimentum.
Cras sed dignissim felis. Maecenas sodales tellus vitae orci placerat interdum. Suspendisse finibus venenatis dignissim. Sed sagittis massa pellentesque rhoncus ultricies. Sed convallis felis lacus, eget suscipit diam vehicula et. Aliquam pellentesque, quam et vestibulum ultricies, quam magna sagittis eros, id vehicula massa nulla in erat. Vestibulum eu facilisis neque, non feugiat neque. Duis condimentum congue pretium. Donec sit amet justo feugiat, ullamcorper ligula id, tempor eros. Sed vitae nulla laoreet, sagittis odio sit amet, porttitor elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer hendrerit, quam ac sodales lacinia, velit libero vulputate urna, et posuere felis nisl et dui. Nunc ut lobortis nisl.
Vivamus accumsan est a libero consectetur, eget pulvinar nunc pretium. Integer at eros quis sem egestas varius. Mauris laoreet convallis imperdiet. Cras quis orci efficitur, luctus tellus ut, pellentesque urna. Phasellus rhoncus pulvinar elementum. Fusce accumsan convallis orci, id ullamcorper nisl laoreet quis. Praesent porttitor magna a justo aliquet hendrerit. Aliquam quis quam augue. Mauris varius malesuada dolor in commodo.
Curabitur in est lectus. Ut tempor dui eu mauris mollis, ut finibus sapien elementum. Donec fringilla tempus erat at sodales. Curabitur viverra volutpat odio non venenatis. Nunc posuere justo ligula, in consectetur lacus aliquet consectetur. Morbi pharetra risus sit amet purus maximus posuere. Nunc vitae est ex. Pellentesque cursus aliquam nibh, sed ornare arcu ultrices eget. Curabitur aliquet sapien ex, non aliquam nibh lacinia ac. Maecenas est sem, vulputate sed mauris in, blandit pharetra mi. Donec non odio non mauris euismod volutpat a vitae ante. Curabitur cursus at enim sed commodo. Phasellus eget turpis non enim vehicula facilisis in ac est.Ut tempor dui eu mauris mollis, ut finibus sapien elementum. Donec fringilla tempus erat at sodales. Curabitur viverra volutpat odio non venenatis. Nunc posuere justo ligula, in consectetur lacus aliquet consectetur. Morbi pharetra risus sit amet purus maximus posuere. Nunc vitae est ex. Pellentesque cursus aliquam nibh, sed ornare arcu ultrices eget. Curabitur aliquet sapien ex, non aliquam nibh lacinia ac. Maecenas est sem, vulputate sed mauris in, blandit pharetra mi. Donec non odio non mauris euismod volutpat a vitae ante. Curabitur cursus at enim sed commodo. Phasellus eget turpis non enim vehicula facilisis in ac est.sdf</p>
    }/>)
}